# Logging
logging:
  file:
    path: /tmp/qod-api-service-logs
  config: classpath:logback-spring.xml

# Health
management:
  server:
    port: 9092
  endpoint:
    health:
      probes:
        enabled: true
    info:
      enabled: true
